#### In numpy, dimentions are axes.
- For example, the coordinates of a point in 3D space [1, 2, 1] has *one axis*. That axis has three elements in it, so we say it has a *length of 3*.
$$\begin{bmatrix} 1. & 0. & 0. \\ 0. & 1. & 2. \end{bmatrix}$$
  - In the matrix above, the array has *2 axes*. The *first axis has a length of 2*, the *second axis has a length of 3*.

In [1]:
import numpy as np

In [2]:
np.array([[1., 0., 0.],[0., 1., 2.]])

array([[1., 0., 0.],
       [0., 1., 2.]])

#### numpy array class is called `ndarray`.

Important attributes of an ndarray object:
- `ndarray.ndim`: the number of axes(dimentions) of the array
- `ndarray.shape`: the dimentions of the array. This is a tuple of integers indicating the size of the array in each dimention. For a matrix with *n rows* and *m columns*, `shape` will be `(n, m)`. The length of the `shape` tuple is therefore the number of the axes, `ndim`.
- `ndarray.size`: the total number of elements in the array. This is equal to the product of the elements of `shape`.
- `ndarray.dtype`: an object describing the type of elements in the array. One can create or specify dtypes using standard python types. Additionally, numpy provides types of its own. `numpy.int32`, `numpy.int16`, and `numpy.float64` are some examples.
- `ndarray.itemsize`: the size in bytes of each element of the array. For example, an array of elements of type `float64` has itemsize 8 (=64/8), while one of the type `complex32` has itemsize 4 (=32/8). It is equivalent to `ndarray.dtype.itemsize`.
- `ndarray.data`: the buffer containing the actual elements of the array. Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities.

In [3]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.size

15

In [7]:
a.dtype

dtype('int32')

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6, 7, 8])
print(b)

[6 7 8]


In [12]:
type(b)

numpy.ndarray

- You can create an array from a regular python list or tuple using the `array` function.

In [13]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [14]:
a.dtype

dtype('int32')